/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ExploreContainer: typeof import('./src/components/ExploreContainer.vue')['default']
    ReaderBookmarks: typeof import('./src/components/reader/ReaderBookmarks.vue')['default']
    ReaderControls: typeof import('./src/components/reader/ReaderControls.vue')['default']
    ReaderNotes: typeof import('./src/components/reader/ReaderNotes.vue')['default']
    ReaderSearch: typeof import('./src/components/reader/ReaderSearch.vue')['default']
    ReaderSettings: typeof import('./src/components/reader/ReaderSettings.vue')['default']
    ReaderTOC: typeof import('./src/components/reader/ReaderTOC.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectionMenu: typeof import('./src/components/reader/SelectionMenu.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
